apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "research-platform.fullname" . }}-api
  labels:
    {{- include "research-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    plane: application
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "research-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "research-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        plane: application
    spec:
      serviceAccountName: {{ include "research-platform.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "research-platform.fullname" . }}-settings
            {{- if .Values.existingSecretName }}
            - secretRef:
                name: {{ .Values.existingSecretName }}
            {{- end }}
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
