apiVersion: v1
kind: Service
metadata:
  name: {{ include "research-platform.fullname" . }}-api
  labels:
    {{- include "research-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
  selector:
    {{- include "research-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
